jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          wget \
          curl \
          unzip \
          libxss1 \
          libappindicator3-1 \
          libindicator7 \
          libgtk-3-0 \
          libgbm1 \
          libasound2 \
          libnss3 \
          libgdk-pixbuf2.0-0 \
          xdg-utils \
          libatk-bridge2.0-0 \
          libatk1.0-0 \
          libnspr4 \
          libx11-xcb1

    - name: Install ChromeDriver and Chrome
      run: |
        # Download and install ChromeDriver
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install ./google-chrome-stable_current_amd64.deb
        # Install the corresponding version of ChromeDriver using webdriver_manager
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager

    - name: Run Python script
      run: |
        python your_script.py
