name: Python CI

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/15 * * * *'  # This will run every 15 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install system dependencies for headless Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          wget \
          curl \
          unzip \
          libxss1 \
          libappindicator3-1 \
          libindicator7 \
          libgtk-3-0 \
          libgbm1 \
          libasound2 \
          libnss3 \
          libgdk-pixbuf2.0-0 \
          xdg-utils \
          libatk-bridge2.0-0 \
          libatk1.0-0 \
          libnspr4 \
          libx11-xcb1

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: |
        python main.py
